### ISSUE TITLE
Fullscreen remains black

### ISSUE THREAD

**Issue by Jigsaw5279** [imakewebthings/deck.js#168]
It seems like if the browser is put into fullscreen mode by `requestFullScreen`, nothing but the status is displayed.

**Comment by imakewebthings** [comment]
@Jigsaw5279 Apparently if you put `.deck-container` into full screen mode, the `auto` width doesn't translate into full width like it does in normal mode. If you want a workaround until I can include this into the next release:

```css
.deck-container:-webkit-full-screen,
.deck-container:fullscreen {
  width:100%;
}
```

Note, I've only seen this problem in Webkit based browsers, Chrome and Safari. I didn't see it in Firefox. I didn't test it in IE 11. Add the `-moz` and `-ms` flavored prefixes if necessary.
